### ISSUE TITLE
When Cropping logs, no indication is given as to the progress

### ISSUE THREAD

**Issue by rjgriffin42** [ihmcrobotics/simulation-construction-set-2#101]
When you go to crop a log, and you hit "open" (the command should be changed), the file chooser window closes, and no confirmation is given that it is actually cropping a log. Then, files start showing up, but the window doesn't display any dialogue that it's actually in the process of generating additional files, so the user doesn't really know what's going on.

**Comment by SylvainBertrand** [comment]
There's a progress information pane, just didn't popup because of an internal exception. Will be fixed in next release
