### ISSUE TITLE
Plotted and visualized values don't update when changed with variable change listener

### ISSUE THREAD

**Issue by rjgriffin42** [ihmcrobotics/simulation-construction-set-2#103]
As an example, I have a simulation where, when I change the desired pole, my PD gains update using a variable change listener. However, the values visualized in SCS2 don't update. I verify that the actual value updates by printing the value, but the plotted (and rendered) value stays the same.

**Comment by rjgriffin42** [comment]
This can be easily seen when changing the damping ratio of a YoPDGains when the "updater" is created. The associated KD value does not update in visualization, but does update in the code.

**Comment by SylvainBertrand** [comment]
This is an issue with some SCS1 tool `MirroredYoVariableRegistry`. I fixed it there, the fix is available in SCS1 0.22.7
