### ISSUE TITLE
Export File could create folders when they don't already exist

### ISSUE THREAD

**Issue by btshrewsbury** [ihmcrobotics/simulation-construction-set-2#106]
Could you add this when you call export? When you programmatically call export, you might want to create new folders at the same time like "c:\sims\Atlas\pushRecovery\20220909\20220909_1302_Atlas_PushWhileWalkingForward\bloop.txt

 private void createParentDirs(File file) throws IOException 
{
      File parent = file.getCanonicalFile().getParentFile();
      if (parent != null && !parent.mkdirs() && !parent.isDirectory()) {
          throw new IOException("Unable to create parent directories of " + file);
      }
  }

**Comment by SylvainBertrand** [comment]
Yup sounds good

**Comment by SylvainBertrand** [comment]
I added that for both video export and sim data export
