### ISSUE TITLE
Easy installer and command line from Linux

### ISSUE THREAD

**Issue by jerryepratt** [ihmcrobotics/simulation-construction-set-2#123]
- Allow passing in arguments for mcap and urdf locations. If mcap, automatically start log visualizer. 

- Better yet, double click an mcap file to start and load it.
- Automatically find the URDF in the same directory (or a remembered directory from the last time) when you load an mcap log. (And could do symbolic link). 
- When loading URDF, look for a resources.zip file in the same directory as the urdf to find the various resources. Automatically look for the resources in the root of that zip, under resources/, resources/models, resources/models/meshes/, resources/meshes, meshes/, models/, and /models/meshes.

**Comment by SylvainBertrand** [comment]
Should we call this issue done?
We can make new issue for specific needs in the feature though
