### ISSUE TITLE
Save MIDI Slider Board Configuration on Exit.

### ISSUE THREAD

**Issue by jerryepratt** [ihmcrobotics/simulation-construction-set-2#131]
When saving the configuration after a run, it would be nice to save the Midi slider board configuration, including the screen and location that the window shows up on. 

Would be nice if you could also minimize the virtual midi window.

**Comment by SylvainBertrand** [comment]
The sliderboard window now gets saved as part of the GUI config.
Also, I changed the window style so you can minimize it.
This is all on develop, feel free to test it and lemme know how it looks

**Comment by jerryepratt** [comment]
Awesome. Thanks, that seems to work!

**Comment by SylvainBertrand** [comment]
I'm gonna close this issue then.
