### ISSUE TITLE
Null Pointer Exception in SimpleColorFX

### ISSUE THREAD

**Issue by jerryepratt** [ihmcrobotics/simulation-construction-set-2#165]
If you go to YoGraphicProperties and create a 2D line and then give it some variable names, you get a null pointer exception in SimpleColorFX().

Quick workaround if you have source is to change line 7 in SimpleColorFX to
   private Color color = Color.RED;

That fixes the null pointer, but now all of your lines are red and seems like they change back to red when you reload each time.

**Comment by SylvainBertrand** [comment]
Ok I just pushed a fix on develop. I'm gonna close this issue, feel free to reopen it if there's something else popping up.
