### ISSUE TITLE
Implement XacroTools to load off the shelf robot models and remove need to vendor redundant URDFs

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#167]
http://wiki.ros.org/xacro is a tool used in ROS and thus many off the shelf robot models are delivered using it. Having a Java implementation to go alongside URDFTools would be very useful and IHMC could use it too to reduce duplication in our URDFs.

**Comment by SylvainBertrand** [comment]
There is no need to embrace xacro for our need, that'd be overkill. It's pretty easy to have multiples URDFs that SCS would combine.
