### ISSUE TITLE
Chart save dialog bad in KDE dark theme

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#19]
![image](https://user-images.githubusercontent.com/1161586/71631422-37581c00-2bce-11ea-9e12-f55fcae01e32.png)

**Comment by SylvainBertrand** [comment]
Not so sure what I can do with this one as the window is handled by the OS and not JavaFX: https://docs.oracle.com/javase/8/javafx/api/javafx/stage/FileChooser.html

**Comment by calvertdw** [comment]
Works great now, haha.
