### ISSUE TITLE
Creates two unhidden directories in user folder, ~/scs2 and ~/SCS2

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#21]
### Current behavior

SCS2 currently creates two unhidden directories in the user home folder, ~/scs2 and ~/SCS2.

### Desired behavior

SCS2 should save to only one hidden folder, i.e. ~/.scs2 or ~/.ihmc/.scs2

**Comment by SylvainBertrand** [comment]
Should be fixed and I moved the folder to .ihmc/scs2
