### ISSUE TITLE
Simulation factory only accepts ROS 2 realtime node (low priority)

### ISSUE THREAD

**Issue by stephenmcc** [ihmcrobotics/simulation-construction-set-2#78]
Most of my sims are setup using the non-realtime node. Any reason for only using realtime?

**Comment by SylvainBertrand** [comment]
Sorry for the long time to come around. So I suppose this is about `SCS2AvatarSimulationFactory.setRealtimeROS2Node(...)`, right?
If that's about that one, it's because the modules the factory is setting  up require a realtime node, it's actually the same as `AvatarSimulationFactory`.
