### ISSUE TITLE
Remote session syntax

### ISSUE THREAD

**Issue by stephenmcc** [ihmcrobotics/simulation-construction-set-2#80]
"Start remote session..." sounds like it will start a server. "Connect to remote session..." would be more clear

**Comment by stephenmcc** [comment]
same for "Start log session". "Open Log" seems more clear

**Comment by SylvainBertrand** [comment]
I'd like to have both named the same, I was thinking about:
- Remote Session Controls...
- Log Session Controls...
That sounds good?

**Comment by stephenmcc** [comment]
I think those are ambiguous esp to a new user. Log Session Controls sounds like you're logging the session. I understand that it's a binary control scheme and makes sense to highlight that. But I'd think "Connect to remote session" and something like "Open Log File" are most clear

**Comment by SylvainBertrand** [comment]
Alright that should be resolved in the next release.
