### ISSUE TITLE
YoVariable input spinners should have color indication when they are being typed in but not applied yet

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#81]
It is not obvious without being an experienced SCS user what the rules are when typing in new values.

**Comment by SylvainBertrand** [comment]
I'm gonna change to match SCS1 behavior, when losing focus the text is updated to the actual current value. This seems like a bug in JavaFX to me.

**Comment by SylvainBertrand** [comment]
Alright that should be resolved in the next release.
