### ISSUE TITLE
Pause button doesn't work during some tests

### ISSUE THREAD

**Issue by rjgriffin42** [ihmcrobotics/simulation-construction-set-2#84]

**Comment by SylvainBertrand** [comment]
If you can provide an example of a test for which you saw that behavior that'd be great

**Comment by rjgriffin42** [comment]
If I set `simulationTestingParameters.keepSCSUp(true)` in `AvatarPushRecoveryOverGapTest.testSidePush`, and then run the test, I would expect to be able to pause the test during execution with the pause button. It just keeps going until the test is finished. In this exact example, it's not a huge deal, but when trying to isolate a bug early in the test, there's no way to prevent the buffer from overwriting once it's full without pausing the test, which currently I don't think I can do.

**Comment by SylvainBertrand** [comment]
Fair, I see what you mean now. Ok I'm gonna look into fixing that

**Comment by SylvainBertrand** [comment]
This should be resolved from version 0.7.0
