### ISSUE TITLE
No way to zoom plotter without a mouse

### ISSUE THREAD

**Issue by rjgriffin42** [ihmcrobotics/simulation-construction-set-2#85]

**Comment by SylvainBertrand** [comment]
Do you mean that you're unable to zoom with a touchpad?

**Comment by rjgriffin42** [comment]
I don't know of a way to zoom with just a touchpad, yeah. If I'm working on a laptop.

**Comment by SylvainBertrand** [comment]
The 2 finger up/down gesture should be recognized as scroll and can be used for zoom

**Comment by SylvainBertrand** [comment]
I'm closing this guy based on our discussion
