### ISSUE TITLE
Saved configuration should include window size and hamburger menu state

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#98]
Having to always be mucking around with the UI to get to things is cognitively distracting when trying to accomplish things. It's be great if configuration would save everything about the way SCS 2 it setup visually.

**Comment by SylvainBertrand** [comment]
It's in except for the camera view, which I'm not seeing yet what type of configuration would be saved yet

**Comment by calvertdw** [comment]
Awesome! I'm not sure either. I'll remove it from the description so this is more closable.
