### ISSUE TITLE
Saving configuration should support saving to the resource folder if working from source

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/simulation-construction-set-2#99]
Saving UI configuration to the resources folder allows for the UI setup to be constant for a simulation across multiple machines, as it can always load the default configuration for a certain commit.

**Comment by calvertdw** [comment]
I have some tools for this WorkspaceDirectory and WorkspaceFile in open robotics. Maybe I could move them to IHMC Commons first.

**Comment by SylvainBertrand** [comment]
In the next release you'll be able to set the home folder for SCS2 (where configuration files are saved) by either using the system property "scs2.home" or the environment variable "SCS2_HOME". Lemme know if that works

**Comment by SylvainBertrand** [comment]
I'm closing this for now. Feel free to reopen if it is still an issue

**Comment by calvertdw** [comment]
Yes this works! Thanks!
